spring:
  datasource:
    url: jdbc:mysql://111.230.31.113:3306/sxx
    driver-class-name: com.mysql.jdbc.Driver
    username: sxx
    password: 1234


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo


logging:
  level:
     com.example.demo.mapper : debug
